language: node_js
node_js:
- 10.9.0
services:
- postgresql
addons:
  postgresql: '9.5'
before_install:
- npm i -g npm@6.9.0
install: case $TRAVIS_BRANCH in greenkeeper*) rm package-lock.json && npm i;; *) npm ci;; esac;
script: npm run cover
before_script:
- npm run db:create
- npm run db:migrate
- npm run db:seed:all
- psql -U postgres -c "create extension fuzzystrmatch"
env:
  global:
  - DB_NAME=ihl_test
  - DB_USERNAME=postgres
  - DB_PASSWORD=""
  - DB_HOST=127.0.0.1
  - DB_LOG_SQL=false
  - COMMAND_PREFIX=!
  - OWNER_DISCORD_ID=76864899866697728
  - CLIENT_ID=360034352853155840
  - CALLBACK_URL=http://127.0.0.1:3000/callback
  - LOGGER_SILENT=false
  - LOGGER_LEVEL=info
  - LOGGER_EXCEPTIONLOGFILE=exceptions.log
  - LOGGER_DIRNAME=logs
  - LOGGER_FILENAME=application-%DATE%.log
  - LOGGER_DATEPATTERN=YYYY-MM-DD-HH
  - LOGGER_ZIPPEDARCHIVE=true
  - LOGGER_MAXSIZE=20m
  - LOGGER_MAXFILES=14d
  - NOCK_BACK_MODE=lockdown
  - secure: HrtS8yPhLA+5455x/77nV0Xnb7FaSnAc4h/pZ5m5RJbeNha2akKgi6AYf3tzGQVw4f3Ytjv7NnEm03jh9g4teP02Dw4OWClFCeycYUEE4SykgeHZI3FOBE7Fz04jESJ8FbQKhLl5d33A3W55uCBG7XrN8fUzpuErODrOex9/ikAyxShFrnD4R2p6i6jpUXCtGSatqWUIqNMUwtVj0ksVG9f3BIQX23hDV1cXgfLc6izBOrIruPA5SMf2ezdZ+ZFSamK3bot44b4/eufS1H2VTt4Z+UnEnzmBs6GoXYpIRac48yQZq7IqfSsU3lx1tT7ZAlpqFmItscIauT78GVDer1CQQwI6rcr9RKbOF0ZpZzxGjcbiVczt+k3HTWdKVPP3Bmpx1Gtetny7kIr4VwzBUo6wzT2qV0aboXcC4Kl210bRXYUml6FesHXVXUhShEbfZxylh+Mbgaw8Phra5Gzl62c1Ct3xbgf4ZBgjhHUg1h3WssjFU69/wWnRAn1UebXBv2onbVnNecdiKZxodnY+Hy4ZHPo3BxoSlGgAnI7VnVguamrUC4eIT/bjDBOccbmThRRpq/2PgXjr67vTly8sEyfDBva+kIHWsGamS6pEmhNd6d+cnpii69QLcN4wglAUIFPCVC1F8JbSZL19CwKyA/eVpCF7EJ6Uoc9gxp+JmWg=
  - secure: TR5WOOdbpdFbV/mMC8jO9e/UmbvDRSFeVW5xQvL6YfHUg/q7C+GKJ+G+3D3AFQojYRH3TUcxMIuFVPctO/S9NGZppGe/lN47jOlxUX4dgvmvW5w1bQQbjMvAD4AEI3CIFDp0ZGiQffQAaSqjxgGZ9F1LHvUPDcF0rEQSy3H1o7zV0vwhezrdS1iBJGh+zK3oT7V37nD7bgRysZKwwRV21fRmYcxVrdkxmF4VHZTvj5q7aCNXpzsjQ1TOnCXV1JciEfcWs/u9Bi1UevvTEaDzHeElWaj8IIFAOIfuGFPzQn8ZicSJwB1H+kkXp+OxHKAdAgMJKUvJRBSkYCk2PNTXVrSW/vKM45DaJ8Uy8KPObEGgloDd1pPmCeeH2SlP48UQWC2wlTxwSSUjHDWNfW5bDk/bvzfdsLSeVB9ptCz+GH7LVOft7ihScuz+PqouUSVzPY3pGi1evyOdZiUjrrp/P6SUr8YBt/m1GL1H4OOBFgGF8POlsjl5THb2Xu8U6s/S0UdEbmwIyMghl5dWLtdBWzAk/u4UW01SfalP1GQkxqHC2wqJ6CvuaRIjcD6g/OyC1H/lvl/1ssDdbANW9eUrOdbdipfpOo88p2Flq0g10zLw3o1Zw52jX0KO9gQ1UmFLAOmSmK4TzoEC2vUoUw1oJjGg6RW86N6WoEpdts6tioY=
  - secure: TvwWC06dORLkfQttG1ZYcejdONf9q35kXtMcbbgeS1x/CNMx29wfwE43CCjVRpNh2uIGbEx1/V6LZpEhytsjwfl8/s2Q9tvDB3sPhNAB0kQSvbFGXf2YTUTyUVMbZpWoetFjdo0mIqTeB4tcb1u4OGDIr9U1tzL6os6vgRkUEVzX/gFdDDJjE/wBo5et9AIBGVliODoTel4j91PL4soF19chyaEkNscrUNF6M+3mFbNSng9dPAiC/8ciXw+MstpAv4vrLkBrH135etJaUtwah/tSoAruBYzJ23Mnxf1729MNYZrWO1W7BNsjWq+QmWYbGf90tnhijEEApiuexhoQM7uJ5wsZQLP4aS5FNysPrZ7H+CBCK1GHcznAD8/Sg/DesnPpSUCEloPD1UBthxDUzuSuOt8uHtUN4RLN4VRB51XHfG/lL+ouOfZclqDKacL0FLesMjy/TLgll3RMKYfrsIQMGAEOsEWC6+r8tw61QYBSpK913RXmXlR7584mJ1BxNczlLM2HkDKfTdUzZcrbjG5ezP1P6foU3vBFjeDNAZxb543fSVATgNcaPxiNAs3lH7Dne4W6VZZ6s6Dcj03RwEzur/p9tSPuL8IAkaLKVXo1UaKYs4az8nN3REwIvtILxrXKGSziu1jGvBr+BgZpxDG4c4S8gUi+OTLJaOF/a1Y=
after_success:
- npm run coveralls